name: Our CI
# what actions trigger the job to be run
on: 
  pull_request:
  push:
    branchs:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Runs tests
      strategy:
      matrix: 
        os : [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.23"]
        include:
        - os: macos-14
          python-version: 3.9
    runs-on: ${{ matrix.os }}
    steps: 
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - if: runner.os == 'Linux'
        run: echo This is Linux
      - run: echo This is ${{ runner.os }}
      - run: python -m pip install .[test]
      # comment
      - name: Run tests
        run: python -m pytest

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test
    steps: 
    - runs: echo "Deploy job"
